### ISSUE TITLE
Create the cirque CLI to chat with cirque service for developer use

### ISSUE THREAD

**Issue by yunhanw-google** [openweave/cirque#3]
cirique-cli would act as the client, and can post several requests to cirque service and orchestrate virtual home topology

for example, create-home "home name", which can create home request to cirque service,
start "docker node name", which can bring up particuler docker 
list "docker node name", which can list the meta data about this node, for example, name, ip address
exec "cmd", which can execute the command,
destroy "home name", which can tear down the home.

**Comment by mingchik** [comment]
done
PR created and merged.
detail please see, PR
https://github.com/openweave/cirque/pull/6
wiki page:
https://github.com/openweave/cirque/wiki/Cirque-Command-Line-Interface
